# Generated by Django 2.2.7 on 2019-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191108_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='is_pablic',
            field=models.BooleanField(default=False),
        ),
    ]
