# Generated by Django 2.2.7 on 2019-11-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_sticky_is_pablic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='category',
            field=models.CharField(choices=[('link', 'link'), ('note', 'note'), ('memo', 'memo'), ('TODO', 'TODO')], max_length=20),
        ),
    ]
