# Generated by Django 2.2.7 on 2019-11-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191109_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticky',
            old_name='is_pablic',
            new_name='is_public',
        ),
    ]
